### ISSUE TITLE
Add ability to comment a block of variables without `///` above every single one.  

### ISSUE THREAD

**Issue by pocketbird** [SassDoc/sassdoc#367] opened 2015-02-12 17:29 UTC
I'd love to comment a block of variables (or anything really) within a page.  For example, it would be nice if the following:

```
///
$brand-color-primary: $654321;
/// 
$brand-color-accent: #123456;
///
$brand-color-warning: #112233;
```

Could just be written as (maybe use 5 slashes?):

```
/////
//// @group brand colors
//// @author pocketbird
$brand-color-primary: $654321;
$brand-color-accent: #123456;
$brand-color-warning: #112233;
/////
```

Comments are meant to clarify your code but, adding `///` above every variable so I can see it in SassDoc makes my code less understandable (especially on larger projects).  My variables don't necessarily need explanation but, it's helpful to have them all listed in SassDoc as a resource.  

Cheers,
Colin

**Comment by HugoGiraudel** [comment] 2015-02-12 18:21
Duplicate of https://github.com/SassDoc/sassdoc/issues/195.

Long story short, there is no way for SassDoc to do that. One possible solution would be to put them all in a file, and use a poster comment.

```scss
////
//// @group brand_colors
//// @author pocketbird
//// @type Color
////

$brand-color-primary: #654321;
$brand-color-accent: #123456;
$brand-color-warning: #112233;
```

**Comment by pascalduez** [comment] 2015-02-12 18:46
Sadly that doesn't work, an item need at least a comment to be processed...

**Comment by pocketbird** [comment] 2015-02-12 19:06
Bummer.  Thanks for the quick reply (and for SassDoc)!  It's seriously rad.

**Comment by HugoGiraudel** [comment] 2015-02-12 19:17
> Sadly that doesn't work, an item needs at least a comment to be processed...

Ah, true. Then, just a single line `///` comment would be enough.

**Closed** 2015-02-13 14:16 UTC
