### ISSUE TITLE
Typo in "csss" string

### ISSUE THREAD

**Issue by barcia** [SassDoc/sassdoc#502] opened 2017-06-07 21:00 UTC
When whe use SassDoc for document a CSS class, in the generated documentation pys "csss" instead "css", I think that is a typo, or not?
![screenshot_20170607_225507](https://user-images.githubusercontent.com/5719646/26901082-d386a6aa-4bd4-11e7-9ff2-8403fed68665.png)

**Comment by pascalduez** [comment] 2017-06-08 08:26
Duplicate of SassDoc/sassdoc-theme-default#92

Thanks for reporting anyway!

**Closed by pascalduez** 2017-06-08 08:26 UTC
