### ISSUE TITLE
Set the default theme's dominant color in config. CSS variables solution, perhaps.

### ISSUE THREAD

**Issue by mkstix6** [SassDoc/sassdoc#485] opened 2017-02-23 19:55 UTC
Firstly, I think the default theme for sassdoc is great.
But I would like to change the `#dd5a6f` pinky color depending on the project without having to build a theme each time.

Would it be possible to pass a color in the sassdoc config. to choose the dominant color found around the docs?

Perhaps CSS variables would solve this elegantly? I don't know sassdoc's internals so this may be a bigger ask than I realise, of course.

Thanks for sassdoc!

**Comment by HugoGiraudel** [comment] 2017-02-23 20:26
Hello. This appears to be a duplicate of https://github.com/SassDoc/sassdoc-theme-default/issues/46 so I’m going to close this one. Please feel free to add any relevant information to the existing issue. :)

**Closed by HugoGiraudel** 2017-02-23 20:26 UTC
