### ISSUE TITLE
group duplicate functions and mixins in requires and used by sections

### ISSUE THREAD

**Issue by chrisopedia** [SassDoc/sassdoc#507] opened 2017-07-18 21:36 UTC
I've notice that if you have a function or mixin used more than once within a mixin, it shows up in the **Requires** and **Used by** sections.  Is it possible to just group those into 1 listing?

**Comment by pascalduez** [comment] 2017-07-19 04:14
Hi,

somehow a dupe of #294.

**Closed** 2017-07-19 04:14 UTC

**Comment by chrisopedia** [comment] 2017-07-19 17:16
🤦‍♂️ sorry, somehow didn't find that one

**Comment by pascalduez** [comment] 2017-07-19 19:28
@chrisopedia No worry !
