### ISSUE TITLE
Add ability to have SassDoc snippets in Sublime Text

### ISSUE THREAD

**Issue by Stephn-R** [SassDoc/sassdoc#422] opened 2015-08-20 21:52 UTC

**Comment by HugoGiraudel** [comment] 2015-08-21 08:04
It's not really up to Sublime Text but to a Docblockr plugin such as: https://github.com/spadgos/sublime-jsdocs. So the best way to go would be to extend this plugin to make it work with SassDoc annotations. :)

**Comment by Stephn-R** [comment] 2015-08-21 15:01
Sounds like a plan :) I am sure we can integrate with DocBlockr for that

**Comment by GitScrum** [comment] 2015-08-21 16:48
+1

**Comment by pascalduez** [comment] 2015-08-21 16:53
Dupe of #204

**Comment by HugoGiraudel** [comment] 2015-11-06 15:56
Not on our side anyway.

**Closed by HugoGiraudel** 2015-11-06 15:56 UTC
Labels: Communication, Feature
