### ISSUE TITLE
engine-strict warning with npm

### ISSUE THREAD

**Issue by krisbulman** [SassDoc/sassdoc#382] opened 2015-03-07 16:38 UTC
Here's what i get on install: 
```
npm WARN engineStrict Per-package engineStrict (found in package.json for sassdoc)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm WARN engine xmlbuilder@2.4.3: wanted: {"node":"0.8.x || 0.10.x || 0.11.x"} (current: {"node":"0.12.0","npm":"2.7.0"})
npm WARN engineStrict Per-package engineStrict (found in package.json for vinyl-fs)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
```

**Comment by valeriangalliat** [comment] 2015-03-07 16:51
Wow we removed `engineStrict` since 2.0 IIRC. But you're right, I can reproduce and I get the same warning, though there's no `engineStrict` at all in SassDoc's `package.json`.

Any idea @pascalduez?

**Comment by pascalduez** [comment] 2015-03-07 18:09
It's an npm issue, see npm/npm#7492

Fixed in `npm@2.7.1` 
`npm install npm@next -g`

**Comment by HugoGiraudel** [comment] 2015-03-19 22:55
Can we close? :)

**Closed** 2015-03-19 23:53 UTC

**Comment by pascalduez** [comment] 2015-03-19 23:54
```
npm dist-tag ls npm
latest: 2.7.1
next: 2.7.3
```
